project:
  type: book
book:
  title: "Data Science for Crime Analysis with Python"
  author: "Andrew P. Wheeler"
  chapters:
    - index.qmd
    - c01.qmd
    - c02.qmd

format:
  pdf:
    pdf-engine: pdflatex
    fontfamily: kpfonts
    monofont: FiraMono
    keep-tex: true
    date: today
    date-format: YYYY-MM-DD
    documentclass: scrbook
    include-in-header:
      - file: packages.tex
    include-before-body: 
      - file: copyright.tex
      - file: macros.tex
    code-block-bg: "#D3D3D3"
    toc: true
    toc-depth: 2
    toc-title: Table of Contents
    colorlinks: true
    papersize: letter
    execute:
        cache: false